import type { Db } from "@/repositories/db";
import { money, type Money } from "@/lib/money";
import { compare, fromDbDate, type CalendarDate } from "@/lib/calendar-date";
import { stepByFrequency } from "@/lib/recurrence";
import * as repo from "@/repositories/income-source-repo";

export interface IncomeEvent {
  date: CalendarDate;
  amount: Money;
  sourceName: string;
}

/**
 * THE shared income source of truth. Every expected income event in [from, to),
 * generated by stepping each IncomeSource's nextDate by its frequency. Both
 * safe-to-spend and the forecast consume only this — they cannot diverge.
 */
export async function projectIncome(
  db: Db,
  workspaceId: string,
  from: CalendarDate,
  to: CalendarDate,
): Promise<IncomeEvent[]> {
  const sources = await repo.listByWorkspace(db, workspaceId);
  const events: IncomeEvent[] = [];
  for (const s of sources) {
    const end = s.endDate ? fromDbDate(s.endDate) : null;
    let cur = fromDbDate(s.nextDate);
    for (let guard = 0; compare(cur, to) < 0 && guard < 2000; guard++) {
      if (end && compare(cur, end) > 0) break;
      if (compare(cur, from) >= 0) {
        events.push({ date: cur, amount: money(s.amount.toFixed(2)), sourceName: s.name });
      }
      cur = stepByFrequency(cur, s.frequency, s.interval, s.dayOfMonth);
    }
  }
  return events.sort((a, b) => compare(a.date, b.date));
}

/** The earliest projected income event on or after `today`. */
export function nextIncomeEvent(events: IncomeEvent[], today: CalendarDate): IncomeEvent | null {
  return events.find((e) => compare(e.date, today) >= 0) ?? null;
}
